/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#4f378a',
        surface: '#fdf7ff',
        'tertiary-fixed-dim': '#e7c365',
        'primary-fixed-dim': '#cfbcff',
        outline: '#7a7582',
        'secondary-fixed-dim': '#cdc0e9',
        'secondary-container': '#e1d4fd',
        'primary-container': '#6750a4',
        tertiary: '#765b00',
        'tertiary-container': '#c9a74d',
        'surface-variant': '#e6e0e9',
        'outline-variant': '#cbc4d2',
        'surface-tint': '#6750a4',
        'surface-container': '#f2ecf4',
        'on-secondary-fixed': '#1f1635',
        'on-tertiary-container': '#503d00',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#594400',
        'secondary-fixed': '#e9ddff',
        background: '#fdf7ff',
        'surface-container-low': '#f8f2fa',
        'on-primary': '#ffffff',
        'inverse-primary': '#cfbcff',
        'on-secondary-fixed-variant': '#4b4263',
        'surface-container-high': '#ece6ee',
        'on-background': '#1d1b20',
        'tertiary-fixed': '#ffdf93',
        'inverse-surface': '#322f35',
        'on-error': '#ffffff',
        'on-secondary-container': '#645a7d',
        'surface-dim': '#ded8e0',
        'on-primary-fixed-variant': '#4f378a',
        'inverse-on-surface': '#f5eff7',
        'primary-fixed': '#e9ddff',
        'on-surface-variant': '#494551',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed': '#241a00',
        'on-primary-fixed': '#22005d',
        'on-surface': '#1d1b20',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#e0d2ff',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        secondary: '#63597c',
        'surface-bright': '#fdf7ff',
        'surface-container-highest': '#e6e0e9',
        'heritage-brown': '#5B3A29',
        'heritage-sand': '#F8F2EC',
        'heritage-ivory': '#FFF9F0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        ROUND_EIGHT: '8px',
      },
      spacing: {
        xl: '64px',
        sm: '12px',
        'margin-mobile': '20px',
        lg: '40px',
        gutter: '16px',
        xs: '4px',
        md: '24px',
        base: '8px',
        'margin-desktop': '120px',
      },
      fontFamily: {
        'display-lg': ['Newsreader', 'serif'],
        'headline-lg': ['Newsreader', 'serif'],
        'headline-md': ['Newsreader', 'serif'],
        'label-lg': ['Work Sans', 'sans-serif'],
        'headline-lg-mobile': ['Newsreader', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-lg': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
